name: yuca_pulso
description: Library containing the specifications of Pulso, Yuca design system
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: YucaIcons
      fonts:
        - asset: packages/yuca_pulso/typography/fonts/YucaIcons.ttf
    - family: Fraunces
      fonts:
        - asset: packages/yuca_pulso/typography/fonts/Fraunces-Black.otf
          weight: 900
        - asset: packages/yuca_pulso/typography/fonts/Fraunces-Regular.ttf
          weight: 400
    - family: Montserrat
      fonts:
        - asset: packages/yuca_pulso/typography/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: packages/yuca_pulso/typography/fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: packages/yuca_pulso/typography/fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: packages/yuca_pulso/typography/fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: packages/yuca_pulso/typography/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: packages/yuca_pulso/typography/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: packages/yuca_pulso/typography/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: packages/yuca_pulso/typography/fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: packages/yuca_pulso/typography/fonts/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: packages/yuca_pulso/typography/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: packages/yuca_pulso/typography/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: packages/yuca_pulso/typography/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: packages/yuca_pulso/typography/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: packages/yuca_pulso/typography/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: packages/yuca_pulso/typography/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: packages/yuca_pulso/typography/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: packages/yuca_pulso/typography/fonts/Montserrat-Black.ttf
          weight: 900